import re

patterns = [
    {
        'label': 'arrayexpress',
        'pattern': r'E\-[A-Z][A-Z][A-Z][A-Z]\-[0-9]+',
        'context_regex': re.compile(r'''(?i)(arrayexpress|atlas|gxa|accession|experiment)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/arrayexpress',
    },
    {
        'label': 'alphafold',
        'pattern': r'AF\-[OPQ][0-9][A-Z0-9][A-Z0-9][A-Z0-9][0-9]+\-F[0-9]',
        'context_regex': re.compile(r'''(?i)(alphafold|alphafold database|alphafold db|structures|predicted structure|predicted protein structure|protein|identifier|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/alphafold',
    },
    {
        'label': 'alphafold',
        'pattern': r'AF\-[A-NR-Z][0-9]([A-Z][A-Z0-9][A-Z0-9][0-9])+\-F[0-9]',
        'context_regex': re.compile(r'''(?i)(alphafold|alphafold database|alphafold db|structures|predicted structure|predicted protein structure|protein|identifier|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/alphafold',
    },
    {
        'label': 'brenda',
        'pattern': r'([0-9]+\.\-\.\-\.\-|[0-9]+\.[0-9]+\.\-\.\-|[0-9]+\.[0-9]+\.[0-9]+\.\-|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)',
        'context_regex': re.compile(r'''(?i)(BRENDA enzyme|BRENDA enzyme database|BRaunschweig ENzyme DAtabase|enzyme database|enzyme|lysosomes|lysosomal|BRENDA:|BRENDA: |BRENDA:EC|BRENDA:EC )''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/brenda',
    },
    {
        'label': 'brenda',
        'pattern': r'BTO: ?([0-9][0-9][0-9][0-9][0-9][0-9][0-9])',
        'context_regex': re.compile(r'''(?i)(BRENDA|BRENDA tissue ontology|BTO|ontology)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/brenda',
    },
    {
        'label': 'bia',
        'pattern': r'S\-BIAD[0-9]+',
        'context_regex': re.compile(r'''(?i)(bia|bioimage archive database|bioimage archive|database|identifier|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/bia',
    },
    {
        'label': 'biomodels',
        'pattern': r'(BIOMD|MODEL)[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(biomodels|accession|model|identifier)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/biomodels.db',
    },
    {
        'label': 'biomodels',
        'pattern': r'BMID[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(biomodels|accession|model|identifier)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/biomodels.db',
    },
    {
        'label': 'biosample',
        'pattern': r'SAM[NED][A-Z]?[0-9]+',
        'context_regex': re.compile(r'''(?i)(biosample|accession|model)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/biosample',
    },
    {
        'label': 'cath',
        'pattern': r'[0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(cath|cath-Gene3D|cath Gene3D|c.a.t.h|domain|families|cathnode|pdb|superfamily)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/cath',
    },
    {
        'label': 'cath',
        'pattern': r'([1-4]\.[0-9]+\.[0-9]+\.[0-9]+)',
        'context_regex': re.compile(r'''(?i)(cath|cath-Gene3D|cath Gene3D|c.a.t.h|domain|families|cathnode|pdb|superfamily)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/cath',
    },
    {
        'label': 'cellosaurus',
        'pattern': r'CVCL_[a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9]',
        'context_regex': re.compile(r'''(?i)(cells|cellosaurus|cellosaurus database|Cell lines|Cell Bank|cell lines|cell bank|accession number|RRID:)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/cellosaurus',
    },
    {
        'label': 'chebi',
        'pattern': r'CHEBI:[0-9]+',
        'context_regex': re.compile(r'''(?i)(chebi|compound)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/chebi',
    },
    {
        'label': 'chembl',
        'pattern': r'CHEMBL[0-9]+',
        'context_regex': re.compile(r'''(?i)(chembl|compound)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/chembl.compound',
    },
    {
        'label': 'complexportal',
        'pattern': r'(CPX)\-[0-9]+',
        'context_regex': re.compile(r'''(?i)(protein|complex)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/complexportal',
    },
    {
        'label': 'metagenomics',
        'pattern': r'SRS[0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(samples|ebi metagenomics|metagenomics|database)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'efo',
        'pattern': r'EFO_[0-9]+',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/efo',
    },
    {
        'label': 'efo',
        'pattern': r'EFO:[0-9]+',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/efo',
    },
    {
        'label': 'ega.study',
        'pattern': r'EGAS[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(ega|accession|archive|studies|study|European Genome-phenome Archive|European Genome phenome Archive)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ega.study',
    },
    {
        'label': 'ega.dataset',
        'pattern': r'EGAD[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(ega|accession|archive|dataset|datasets|data set|data sets|validation sets|validation set|set|sets|data|European Genome-phenome Archive|European Genome phenome Archive)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ega.dataset',
    },
    {
        'label': 'ega.dac',
        'pattern': r'EGAC[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(ega|accession|archive|dac|European Genome-phenome Archive|European Genome phenome Archive)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ega.dac',
    },
    {
        'label': 'emdb',
        'pattern': r'EMD\-[0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(emdb|accession|code)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/emdb',
    },
    {
        'label': 'empiar',
        'pattern': r'EMPIAR\-[0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(Electron Microscopy Public Image Archive|EMPIAR database|EMPIAR|database|accession|code)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/empiar',
    },
    {
        'label': 'empiar',
        'pattern': r'EMPIAR\-[0-9][0-9][0-9][0-9][0-9]',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/empiar',
    },
    {
        'label': 'gen',
        'pattern': r'[A-Z][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|asssembled|annotated|sequence|sequences)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'[A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|asssembled|annotated|sequence|sequences)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'[A-RT-Z][A-Z][A-Z][A-Z][S]?[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]([0-9])?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|asssembled|annotated|sequence|sequences)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|protein coding|protein|sequence|sequences)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'TI[0-9]+',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|trace|traces)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'(E|D|S)RP[0-9][0-9][0-9][0-9][0-9]([0-9]+)?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|study|studies)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'ERS[0-9][0-9][0-9][0-9][0-9]([0-9]+)?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|sample|samples)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'(E|D|S)RX[0-9][0-9][0-9][0-9][0-9]([0-9]+)?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|experiment|experiments)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'(E|D|S)RR[0-9][0-9][0-9][0-9][0-9]([0-9]+)?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|run|runs)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'(E|D|S)RZ[0-9][0-9][0-9][0-9][0-9]([0-9]+)?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|analysis|analyses)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'gen',
        'pattern': r'(E|D|S)RA[0-9][0-9][0-9][0-9][0-9]([0-9]+)?',
        'context_regex': re.compile(r'''(?i)(genbank|\bgen\b|\bena\b|ddbj|embl|european nucleotide archive|accession|nucleotide|archive|submission|submissions)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/ena.embl',
    },
    {
        'label': 'ensembl',
        'pattern': r'[eE][nN][sS][a-zA-Z]*[gG][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]+',
        'context_regex': re.compile(r'''(?i)(ensembl|accession|transcript|sequence)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ensembl',
    },
    {
        'label': 'ensembl',
        'pattern': r'[eE][nN][sS][a-zA-Z]*[ptPT][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]+',
        'context_regex': re.compile(r'''(?i)(ensembl|accession|transcript|sequence)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ensembl',
    },
    {
        'label': 'go',
        'pattern': r'GO:[0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(go|gene ontology)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/go',
    },
    {
        'label': 'hgnc',
        'pattern': r'HGNC:[0-9]+',
        'context_regex': re.compile(r'''(?i)(HUGO Gene Nomenclature Committee|hugo|gene|nomenclature|committee|database)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/hgnc',
    },
    {
        'label': 'hpa',
        'pattern': r'(HPA|hpa)[0-9][0-9][0-9][0-9][0-9][0-9]',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/hpa',
    },
    {
        'label': 'hpa',
        'pattern': r'(CAB|cab)[0-9][0-9][0-9][0-9][0-9][0-9]',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/hpa',
    },
    {
        'label': 'igsr',
        'pattern': r'HG0[0-4][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(\bcell\b|sample|iPSC|iPSCs|iPS|fibroblast|fibroblasts|QTL|eQTL|pluripotent|induced|\bdonor\b|\bstem\b|EBiSC|1000 Genomes|Coriell|\bLCL\b|lymphoblastoid)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/coriell',
    },
    {
        'label': 'igsr',
        'pattern': r'(NA|GM)[0-2][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(\bcell\b|sample|iPSC|iPSCs|iPS|fibroblast|fibroblasts|QTL|eQTL|pluripotent|induced|\bdonor\b|\bstem\b|EBiSC|1000 Genomes|Coriell|\bLCL\b|lymphoblastoid)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/coriell',
    },
    {
        'label': 'intact',
        'pattern': r'EBI\-[0-9]+',
        'context_regex': re.compile(r'''(?i)(intact|IntAct|inTact|Intact|interaction|interactions|protein)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/intact',
    },
    {
        'label': 'mint',
        'pattern': r'MINT\-[0-9]+|IM\-[0-9]+',
        'context_regex': re.compile(r'''(?i)(MINT|molecular interaction database|interactions|interaction)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/mint',
    },
    {
        'label': 'interpro',
        'pattern': r'[iI][pP][rR][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(interpro|domain|family|motif|accession)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/interpro',
    },
    {
        'label': 'metabolights',
        'pattern': r'MTBLS[0-9]+',
        'context_regex': re.compile(r'''(?i)(metabolights|accession|repository)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/metabolights',
    },
    {
        'label': 'pdb',
        'pattern': r'[0-9][a-zA-Z0-9]{3}',
        'context_regex': re.compile(r'''(?i)(pdb|(?:protein +data *bank)|accession|structure|accession|domain)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/pdbe/pdb',
    },
    {
        'label': 'pfam',
        'pattern': r'PF(AM)?[0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(pfam|domain|family|accession|motif)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/pfam',
    },
    {
        'label': 'pxd',
        'pattern': r'(R)?PXD[0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(pxd|proteomexchange|pride|dataset|accession|repository)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/pxd',
    },
    {
        'label': 'reactome',
        'pattern': r'R\-HSA\-[0-9]+',
        'context_regex': re.compile(r'''(?i)(biological|regulatory|pathway|pathways|database)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/reactome',
    },
    {
        'label': 'rfam',
        'pattern': r'RF[0-9][0-9][0-9][0-9][0-9]',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/rfam',
    },
    {
        'label': 'rhea',
        'pattern': r'[Rr][Hh][Ee][Aa]\:[1-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(reactions|database|rhea database|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/rhea',
    },
    {
        'label': 'rhea',
        'pattern': r'[Rr][Hh][Ee][Aa]\:[1-9][0-9]+',
        'context_regex': re.compile(r'''(?i)(reactions|database|rhea database|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/rhea',
    },
    {
        'label': 'rhea',
        'pattern': r'[Rr][Hh][Ee][Aa]\:[1-9][0-9]+',
        'validation_method': 'noval',
        'normalization_url': 'http://identifiers.org/rhea',
    },
    {
        'label': 'rnacentral',
        'pattern': r'URS[0-9A-Z]+_[0-9]+',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/rnacentral',
    },
    {
        'label': 'uniprot',
        'pattern': r'([a-nr-zA-NR-Z][0-9][a-zA-Z][a-zA-Z0-9][a-zA-Z0-9][0-9]|[opqOPQ][0-9][a-zA-Z0-9][a-zA-Z0-9][a-zA-Z0-9][0-9])([-][0-9]+)?',
        'context_regex': re.compile(r'''(?i)(swiss-prot|sprot|uniprot|swiss prot|accession(s)?|Locus|GenBank|genome|sequence(s)?|protein|trembl|uniparc|uniprotkb|Acc.No|Acc. No)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/uniprot',
    },
    {
        'label': 'uniparc',
        'pattern': r'UPI[A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9]',
        'context_regex': re.compile(r'''(?i)(uniprot|accession(s)?|Locus|sequence(s)?|protein|uniparc|Acc.No|Acc. No)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/uniparc',
    },
    {
        'label': 'ebisc',
        'pattern': r'[A-Z][A-Z]+i[0-9][0-9][0-9]\-[A-Z]',
        'context_regex': re.compile(r'''(\bcell\b|sample|iPSC|iPSCs|iPS|fibroblast|fibroblasts|QTL|eQTL|pluripotent|induced|\bdonor\b|\bstem\b|EBiSC|1000 Genomes|Coriell|\bLCL\b|lymphoblastoid)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebisc',
    },
    {
        'label': 'hipsci',
        'pattern': r'HPSI[0-9][0-9][0-9][0-9](i|pf)\-[a-z]+_[0-9]+',
        'context_regex': re.compile(r'''(\bcell\b|sample|iPSC|iPSCs|iPS|fibroblast|fibroblasts|QTL|eQTL|pluripotent|induced|\bdonor\b|\bstem\b|EBiSC|1000 Genomes|Coriell|\bLCL\b|lymphoblastoid)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/hipsci',
    },
    {
        'label': 'refseq',
        'pattern': r'(AC|AP|NC|NG|NM|NP|NR|NT|NW|NZ|XM|XP|XR|YP|ZP|NS)_([A-Z][A-Z][A-Z][A-Z])*[0-9][0-9][0-9][0-9][0-9][0-9][0-9]?[0-9]?[0-9]?([.][0-9]+)?',
        'context_regex': re.compile(r'''(?i)(refseq|genbank|accession|sequence)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/refseq',
    },
    {
        'label': 'refsnp',
        'pattern': r'[rs]s[0-9][0-9]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?[0-9]?',
        'context_regex': re.compile(r'''(?i)(allele|model|multivariate|polymorphism|locus|loci|haplotype|genotype|variant|chromosome|SNPs|snp|snp(s)*)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/dbsnp',
    },
    {
        'label': 'doi',
        'pattern': r'10\.[0-9][0-9][0-9][0-9]+/[^ ()\"<>]+',
        'context_regex': re.compile(r'''(?i)(doi|repository)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/doi',
    },
    {
        'label': 'bioproject',
        'pattern': r'PRJ[DEN][A-Z][0-9]+',
        'context_regex': re.compile(r'''(?i)(bioproject|accession|archive)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/ebi/bioproject',
    },
    {
        'label': 'gca',
        'pattern': r'GCA_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]([.][0-9]+)?',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/insdc.gca',
    },
    {
        'label': 'treefam',
        'pattern': r'TF[0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(treefam|tree|family|accession|dendrogram)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/treefam',
    },
    {
        'label': 'eudract',
        'pattern': r'[0-9][0-9][0-9][0-9]\-[0-9][0-9][0-9][0-9][0-9][0-9]\-[0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(eudract|trial|agency|register|clinical)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/euclinicaltrials',
    },
    {
        'label': 'nct',
        'pattern': r'NCT[0-0][0-9][0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(trial)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/clinicaltrials',
    },
    {
        'label': 'dbgap',
        'pattern': r'phs[0-9][0-9][0-9][0-9][0-9][0-9]',
        'context_regex': re.compile(r'''(?i)(database of genotypes and phenotypes|dbgap|accession|archives|studies|interaction)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/dbgap',
    },
    {
        'label': 'geo',
        'pattern': r'G(PL|SM|SE|DS)[0-9][0-9]+',
        'context_regex': re.compile(r'''(?i)(gene expression omnibus|genome|geo|accession|functional genomics|data repository|data submissions)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/geo',
    },
    {
        'label': 'gse',
        'pattern': r'GSE[0-9]+',
        'validation_method': 'noval',
        'normalization_url': 'http://identifiers.org/geo',
    },
    {
        'label': 'orphadata',
        'pattern': r'ORPHA:[0-9]+',
        'context_regex': re.compile(r'''(?i)(database|rare disease|disease|nomenclature|data|syndrome|id|number|name|orphanet|orphadata|orpha)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/orphadata',
    },
    {
        'label': 'orphadata',
        'pattern': r'ORPHA [0-9]+',
        'context_regex': re.compile(r'''(?i)(database|rare disease|disease|data|nomenclature|syndrome|id|number|name|orphanet|orphadata|orpha)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/orphadata',
    },
    {
        'label': 'gisaid',
        'pattern': r'EPI[0-9][0-9][0-9][0-9][0-9][0-9]+',
        'context_regex': re.compile(r'''(?i)(gisaid|global initiative on sharing all influenza data|segment|segments|identifier|flu|epi|epiflu|database|sequence|sequences|isolate|isolates|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/gisaid',
    },
    {
        'label': 'gisaid',
        'pattern': r'EPI[0-9][0-9][0-9][0-9][0-9][0-9]\-[0-9]+',
        'context_regex': re.compile(r'''(?i)(gisaid|global initiative on sharing all influenza data|segment|segments|identifier|flu|epi|epiflu|database|sequence|sequences|isolate|isolates|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/gisaid',
    },
    {
        'label': 'gisaid',
        'pattern': r'EPI_ISL_[0-9][0-9][0-9][0-9][0-9][0-9]+',
        'context_regex': re.compile(r'''(?i)(gisaid|global initiative on sharing all influenza data|virus|viruses|strain|strains|sequence|sequences|flu|epiflu|identifier|database|accession)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://identifiers.org/gisaid',
    },
    {
        'label': 'biostudies',
        'pattern': r'S\-[A-Z][A-Z][A-Z][A-Z][A-Z0-9\-]+',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/biostudies',
    },
    {
        'label': 'rrid',
        'pattern': r'RRID:\s*AB_[0-9][0-9][0-9][0-9][0-9][0-9][0-9]+',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/rrid',
    },
    {
        'label': 'rrid',
        'pattern': r'RRID:\s*SCR_[0-9][0-9][0-9][0-9][0-9][0-9]',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/rrid',
    },
    {
        'label': 'rrid',
        'pattern': r'RRID:\s*CVCL_[A-Z0-9][A-Z0-9][A-Z0-9][A-Z0-9]',
        'validation_method': 'online',
        'normalization_url': 'http://identifiers.org/rrid',
    },
    {
        'label': 'omim',
        'pattern': r'[0-9]{6}',
        'context_regex': re.compile(r'''(?i)(o*mim|syndrome|disease|deficiency)''', re.IGNORECASE),
        'validation_method': 'onlineWithContext',
        'normalization_url': 'http://identifiers.org/omim',
    },
    {
        'label': 'Rcellosaurus',
        'pattern': r'Cellosaurus|cellosaurus',
        'context_regex': re.compile(r'''(?i)(database|cells|Cell lines|Cell Bank|cell lines|cell bank)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00000598',
    },
    {
        'label': 'Rcellosaurus',
        'pattern': r'Cellosaurus database|cellosaurus database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000598',
    },
    {
        'label': 'Rrhea',
        'pattern': r'Rhea',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000827',
    },
    {
        'label': 'Rrhea',
        'pattern': r'Rhea knowledgebase|Rhea Knowledgebase|RHEA knowledgebase|RHEA Knowledge',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000827',
    },
    {
        'label': 'Rrhea',
        'pattern': r'RHEA database|RHEA Database|Rhea database|Rhea Database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000827',
    },
    {
        'label': 'Rrhea',
        'pattern': r'Rhea reaction|Rhea Reaction|RHEA reaction|RHEA Reaction',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000827',
    },
    {
        'label': 'Ralphafold',
        'pattern': r'Alphafold|alphafold',
        'context_regex': re.compile(r'''(?i)(database|cells|Cell lines|Cell Bank|cell lines|cell bank)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://alphafold.ebi.ac.uk/',
    },
    {
        'label': 'Ralphafold',
        'pattern': r'Alphafold database|alphafold database|Alphafold Database',
        'validation_method': 'noval',
        'normalization_url': 'https://alphafold.ebi.ac.uk/',
    },
    {
        'label': 'Rarrayexpress',
        'pattern': r'ArrayExpress',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100061',
    },
    {
        'label': 'Rarrayexpress',
        'pattern': r'Array Express',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100061',
    },
    {
        'label': 'Rbiomodels',
        'pattern': r'BioModels',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100006',
    },
    {
        'label': 'Rbia',
        'pattern': r'BioImage Archive|bioimage archive',
        'validation_method': 'noval',
        'normalization_url': 'https://www.ebi.ac.uk/bioimage-archive/',
    },
    {
        'label': 'Rbia',
        'pattern': r'BioImage Archive Database|bioImage archive database',
        'validation_method': 'noval',
        'normalization_url': 'https://www.ebi.ac.uk/bioimage-archive/',
    },
    {
        'label': 'Rbiosamples',
        'pattern': r'[Bb]io[Ss]amples',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100447',
    },
    {
        'label': 'Rbiosamples',
        'pattern': r'BioSD|Biosd',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100447',
    },
    {
        'label': 'Rbiostudies',
        'pattern': r'BioStudies',
        'validation_method': 'noval',
        'normalization_url': 'http://www.ebi.ac.uk/biostudies',
    },
    {
        'label': 'Rcath',
        'pattern': r'CATH',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100816',
    },
    {
        'label': 'Rcath',
        'pattern': r'Cath',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100816',
    },
    {
        'label': 'Rcath',
        'pattern': r'CATH Gene3D|Cath Gene3D|cath gene3D',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100816',
    },
    {
        'label': 'Rcath',
        'pattern': r'CATH[\-]Gene3D',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100816',
    },
    {
        'label': 'Rcath',
        'pattern': r'Cath[\-]Gene3D',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100816',
    },
    {
        'label': 'Rcath',
        'pattern': r'C.A.T.H',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100816',
    },
    {
        'label': 'Rchebi',
        'pattern': r'ChEBI',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100009',
    },
    {
        'label': 'Rchebi',
        'pattern': r'Chemical Entities of Biological Interest',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100009',
    },
    {
        'label': 'Rchembl',
        'pattern': r'ChEMBL',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100115',
    },
    {
        'label': 'Rchembl',
        'pattern': r'UniChem',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100115',
    },
    {
        'label': 'Rcomplexportal',
        'pattern': r'Complex Portal',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100875',
    },
    {
        'label': 'Rmetagenomics',
        'pattern': r'EBI Metagenomics',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100656',
    },
    {
        'label': 'Refo',
        'pattern': r'Experimental Factor Ontology',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100511',
    },
    {
        'label': 'Refo',
        'pattern': r'EFO',
        'context_regex': re.compile(r'''(?i)(experimental|factor|ontology)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100511',
    },
    {
        'label': 'Rega',
        'pattern': r'EGA',
        'context_regex': re.compile(r'''(?i)(european|genome|phenome|archive)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100658',
    },
    {
        'label': 'Rega',
        'pattern': r'European Genome\-phenome Archive',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100658',
    },
    {
        'label': 'Remdb',
        'pattern': r'Electron Microscopy Data Bank',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100738',
    },
    {
        'label': 'Remdb',
        'pattern': r'EMDataBank',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100738',
    },
    {
        'label': 'Rempiar',
        'pattern': r'Electron Microscopy Public Image Archive',
        'validation_method': 'noval',
        'normalization_url': 'http://www.ebi.ac.uk/pdbe/emdb/empiar',
    },
    {
        'label': 'Rempiar',
        'pattern': r'EMPIAR',
        'validation_method': 'noval',
        'normalization_url': 'http://www.ebi.ac.uk/pdbe/emdb/empiar',
    },
    {
        'label': 'Rempiar',
        'pattern': r'EMPIAR',
        'context_regex': re.compile(r'''(?i)(image|deposit)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://www.ebi.ac.uk/pdbe/emdb/empiar',
    },
    {
        'label': 'Rena',
        'pattern': r'ENA',
        'context_regex': re.compile(r'''(?i)(nucleotide|archive)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100473',
    },
    {
        'label': 'Rena',
        'pattern': r'European Nucleotide Archive',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100473',
    },
    {
        'label': 'Rena',
        'pattern': r'EMBL Nucleotide Sequence Database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100473',
    },
    {
        'label': 'Rensembl',
        'pattern': r'Ensembl',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100011',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Gg]enomes',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Bb]acteria',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Ff]ungi',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Mm]etazoa',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Pp]lants',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Pp]rotists',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Gg]enomes [Bb]acteria',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Gg]enomes [Ff]ungi',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Gg]enomes [Mm]etazoa',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Gg]enomes [Pp]lants',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Rensemblgenomes',
        'pattern': r'Ensembl [Gg]enomes [Pp]rotists',
        'validation_method': 'noval',
        'normalization_url': 'http://ensemblgenomes.org',
    },
    {
        'label': 'Repmc',
        'pattern': r'EuropePMC',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100497',
    },
    {
        'label': 'Repmc',
        'pattern': r'Europe PMC',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100497',
    },
    {
        'label': 'Repmc',
        'pattern': r'Europe PubMed Central',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100497',
    },
    {
        'label': 'Repmc',
        'pattern': r'europepmc\.org',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100497',
    },
    {
        'label': 'Reva',
        'pattern': r'[Ee]uropean [Vv]ariation [Aa]rchive',
        'validation_method': 'noval',
        'normalization_url': 'http://www.ebi.ac.uk/eva',
    },
    {
        'label': 'Reva',
        'pattern': r'EVA',
        'context_regex': re.compile(r'''(?i)(allele|model|multivariate|polymorphism|locus|loci|haplotype|genotype|variant|chromosome|SNPs|snp|European Variation Archive|variation|archive|gene)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://www.ebi.ac.uk/eva',
    },
    {
        'label': 'Rgxa',
        'pattern': r'Expression Atlas',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100482',
    },
    {
        'label': 'Rgo',
        'pattern': r'Gene Ontology',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100013',
    },
    {
        'label': 'Rgwas',
        'pattern': r'GWAS Catalog',
        'validation_method': 'noval',
        'normalization_url': 'http://www.ebi.ac.uk/gwas',
    },
    {
        'label': 'Rhgnc',
        'pattern': r'HGNC',
        'context_regex': re.compile(r'''(?i)(HUGO Gene Nomenclature Committee|hugo|gene|nomenclature|committee)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100460',
    },
    {
        'label': 'Rhgnc',
        'pattern': r'HUGO Gene Nomenclature Committee',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100460',
    },
    {
        'label': 'Rhpa',
        'pattern': r'[Hh]uman [Pp]rotein [Aa]tlas',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100431',
    },
    {
        'label': 'Rhpa',
        'pattern': r'HPA|hpa',
        'context_regex': re.compile(r'''(?i)(human|protein|atlas)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100431',
    },
    {
        'label': 'Rhpa',
        'pattern': r'[Pp]roteinatlas',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100431',
    },
    {
        'label': 'Rhpa',
        'pattern': r'proteinatlas\.org',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100431',
    },
    {
        'label': 'Rhpa',
        'pattern': r'[Pp]rotein [Aa]tlas',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100431',
    },
    {
        'label': 'Ridentifiers',
        'pattern': r'identifiers\.org',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100800',
    },
    {
        'label': 'Rigsr',
        'pattern': r'International Genome Sample Resource',
        'validation_method': 'noval',
        'normalization_url': 'http://www.internationalgenome.org',
    },
    {
        'label': 'Rigsr',
        'pattern': r'1000 Genomes',
        'validation_method': 'noval',
        'normalization_url': 'http://www.internationalgenome.org',
    },
    {
        'label': 'Rintact',
        'pattern': r'IntAct',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100017',
    },
    {
        'label': 'Rintact',
        'pattern': r'[Ii]nt[Aa]ct database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100017',
    },
    {
        'label': 'Rmint',
        'pattern': r'[Mm]olecular [Ii][Nn][Tt]eraction [Dd]atabase',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100654',
    },
    {
        'label': 'Rmint',
        'pattern': r'[Mm][Ii][Nn][Tt]',
        'context_regex': re.compile(r'''(?i)(database|interaction)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100654',
    },
    {
        'label': 'Rinterpro',
        'pattern': r'InterPro',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100018',
    },
    {
        'label': 'Rinterpro',
        'pattern': r'InterProScan',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100018',
    },
    {
        'label': 'Rmetabolights',
        'pattern': r'MetaboLights',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100486',
    },
    {
        'label': 'Rols',
        'pattern': r'Ontology Lookup Service',
        'validation_method': 'noval',
        'normalization_url': 'http://www.ebi.ac.uk/ols',
    },
    {
        'label': 'Rols',
        'pattern': r'OLS',
        'context_regex': re.compile(r'''(?i)(Ontology|Lookup|Service)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://www.ebi.ac.uk/ols',
    },
    {
        'label': 'Rpdb',
        'pattern': r'PDB',
        'context_regex': re.compile(r'''(?i)(protein|data|bank)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'Protein Databank',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'Protein DataBank',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'Protein Data Bank',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'PDBe',
        'context_regex': re.compile(r'''(?i)(protein|data|bank|europe)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'Protein Databank in Europe',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'Protein DataBank in Europe',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'Protein Data Bank in Europe',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpdb',
        'pattern': r'RCSB PDB',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100037',
    },
    {
        'label': 'Rpfam',
        'pattern': r'Pfam',
        'context_regex': re.compile(r'''(?i)(protein|family|database|enzyme)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100685',
    },
    {
        'label': 'Rpfam',
        'pattern': r'Protein Family Database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100685',
    },
    {
        'label': 'Rpride',
        'pattern': r'PRIDE',
        'context_regex': re.compile(r'''(?i)(proteomics|identifications|database)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100094',
    },
    {
        'label': 'Rpride',
        'pattern': r'PRoteomics IDEntifications database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100094',
    },
    {
        'label': 'Rreactome',
        'pattern': r'Reactome',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100026',
    },
    {
        'label': 'Rrfam',
        'pattern': r'Rfam',
        'context_regex': re.compile(r'''(?i)(RNA|families|database)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100686',
    },
    {
        'label': 'Rrnacentral',
        'pattern': r'RNAcentral',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100834',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'STRING',
        'context_regex': re.compile(r'''(?i)(database|interaction|network)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'STRING-DB|string-db|String-DB|String-db',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'(String|string) (db|DB)',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'STRING-[Dd]atabase',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'(STRING|string|String) [Dd]atabase',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'(STRING|string|String) [Ii]nteraction [Dd]atabase',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'(STRING|string|String) [Nn]etwork',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'database (STRING|String|string)',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'https://string-db.org',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'http://string-db.org',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'string-db.org',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'string.embl.de',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rstringdb',
        'pattern': r'[Dd]atabase(\(STRING\)|\(String\)|\(string\))',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100342',
    },
    {
        'label': 'Rsurechembl',
        'pattern': r'SureChEMBL',
        'validation_method': 'noval',
        'normalization_url': 'http://www.surechembl.org',
    },
    {
        'label': 'Runiprot',
        'pattern': r'UniProt|Uniprot|uniprot|uniProt|UNIPROT',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Runiprot',
        'pattern': r'Uniref|UniRef|uniref|uniRef|UNIREF',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Runiprot',
        'pattern': r'Uniparc|UniParc|uniParc|uniparc|UNIP[Aa]RC',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Runiprot',
        'pattern': r'Trembl|trembl|TREMBL|TrEMBL|TrEmbl',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Runiprot',
        'pattern': r'UniProtKB|Uniprotkb|UniprotKB|UNIPROTKB|uniProtKB|uniprotkb|uniprotKB|UNIPROTKB',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Runiprot',
        'pattern': r'SwissProt|swissProt|swissprot|Swissprot|SWISSPROT',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Runiprot',
        'pattern': r'Swiss-Prot|Swiss-prot|swiss-Prot|swiss-prot|SWISS-PROT',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100164',
    },
    {
        'label': 'Rvectorbase',
        'pattern': r'VectorBase',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100291',
    },
    {
        'label': 'Rwormbase',
        'pattern': r'WormBase',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00100038',
    },
    {
        'label': 'Rbrenda',
        'pattern': r'Brenda|BRENDA',
        'context_regex': re.compile(r'''(?i)(database|enzyme database)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://identifiers.org/MIR:00000071',
    },
    {
        'label': 'Rbrenda',
        'pattern': r'BRENDA',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000071',
    },
    {
        'label': 'Rbrenda',
        'pattern': r'BRENDA enzyme database',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000071',
    },
    {
        'label': 'Rbrenda',
        'pattern': r'BRENDA (database|db|DB)',
        'validation_method': 'noval',
        'normalization_url': 'https://identifiers.org/MIR:00000071',
    },
    {
        'label': 'Rsilva',
        'pattern': r'Silva|SILVA',
        'context_regex': re.compile(r'''(?i)(database|ribosomal RNA|rRNA|rDNA|ribosomal RNA sequence data|rDNA sequence)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rsilva',
        'pattern': r'SILVA',
        'validation_method': 'noval',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rsilva',
        'pattern': r'SILVA ribosomal RNA',
        'validation_method': 'noval',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rsilva',
        'pattern': r'SILVA rDNA',
        'validation_method': 'noval',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rsilva',
        'pattern': r'SILVA rRNA',
        'validation_method': 'noval',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rsilva',
        'pattern': r'SILVA (database|db|DB)',
        'validation_method': 'noval',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rsilva',
        'pattern': r'SILVA rRNA database',
        'validation_method': 'noval',
        'normalization_url': 'https://www.arb-silva.de',
    },
    {
        'label': 'Rorphadata',
        'pattern': r'ORPHADATA|Orphadata|orphadata',
        'context_regex': re.compile(r'''(?i)(database|rare disease|disease|nomenclature|syndrome|data|orpha|orphanet|orphanet rare disease ontology|orphanet vocabulary)''', re.IGNORECASE),
        'validation_method': 'contextOnly',
        'normalization_url': 'http://www.orphadata.org',
    },
    {
        'label': 'Rorphadata',
        'pattern': r'ORPHADATA|Orphadata|orphadata',
        'validation_method': 'noval',
        'normalization_url': 'http://www.orphadata.org',
    },
    {
        'label': 'Rorphadata',
        'pattern': r'(ORPHADATA|Orphadata|orphadata) database',
        'validation_method': 'noval',
        'normalization_url': 'http://www.orphadata.org',
    },
]

blacklist = [
    r'<z:[^>]*>(.*</z)!:[^>]*>',
    r'="([^">]*)"',
    r'GM06326',
    r'GM07226',
    r'GM07257',
    r'GM07270',
    r'GM07347',
    r'GM07367',
    r'GM07464',
    r'GM07499',
    r'GM07517',
    r'GM07544',
    r'GM08249',
    r'GM08322',
    r'GM08425',
    r'GM08570',
    r'GM08659',
    r'GM08704',
    r'GM15431',
    r'GM21422',
    r'GM21841',
    r'GM22939',
    r'GM23377',
    r'GM24663',
    r'GM24872',
    r'GM25232',
    r'GM25661',
    r'GM26017',
    r'GM26938',
    r'GM28016',
    r'GM28157',
    r'GM28454',
    r'GM28630',
    r'HG00046',
    r'HG01880',
    r'HG02357',
    r'HG02370',
    r'HG02523',
    r'HG02790',
    r'HG03067',
    r'NA12878',
    r'NA15510',
    r'[0-9][0-9][0-9][0-9]',
    r'</?[A-Za-z_0-9\-]+[^>]+>',
    r'<z:[^>]*>(.*</z)!:[^>]*>',
    r'="([^">]*)"',
    r'GM06326',
    r'GM07226',
    r'GM07257',
    r'GM07270',
    r'GM07347',
    r'GM07367',
    r'GM07464',
    r'GM07499',
    r'GM07517',
    r'GM07544',
    r'GM08249',
    r'GM08322',
    r'GM08425',
    r'GM08570',
    r'GM08659',
    r'GM08704',
    r'GM15431',
    r'GM21422',
    r'GM21841',
    r'GM22939',
    r'GM23377',
    r'GM24663',
    r'GM24872',
    r'GM25232',
    r'GM25661',
    r'GM26017',
    r'GM26938',
    r'GM28016',
    r'GM28157',
    r'GM28454',
    r'GM28630',
    r'HG00046',
    r'HG01880',
    r'HG02357',
    r'HG02370',
    r'HG02523',
    r'HG02790',
    r'HG03067',
    r'NA12878',
    r'NA15510',
    r'[0-9][0-9][0-9][0-9]',
    r'</?[A-Za-z_0-9\-]+[^>]+>',
    r'<z:[^>]*>(.*</z)!:[^>]*>',
    r'="([^"]*)"',
]
